# Generated by Django 3.2.5 on 2021-07-17 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0003_auto_20210717_1104'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profilemodel',
            name='games_interest',
            field=models.ManyToManyField(to='masters.Game'),
        ),
    ]
