# Generated by Django 3.2.5 on 2021-07-17 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0002_alter_game_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='game',
            name='no_of_players',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='game',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
