# Generated by Django 3.2.5 on 2021-07-29 13:37

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
        ('masters', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HostGame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='')),
                ('players_team', models.CharField(choices=[('players', 'players'), ('teams', 'teams')], max_length=20)),
                ('no_of_players', models.IntegerField()),
                ('no_of_teams', models.IntegerField()),
                ('no_of_players_in_team', models.IntegerField()),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.BooleanField(default=True)),
                ('start_datetime', models.DateTimeField(default=django.utils.timezone.now)),
                ('end_date_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='masters.game')),
            ],
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('start_datetime', models.DateTimeField(default=django.utils.timezone.now)),
                ('end_datetime', models.DateTimeField(default=django.utils.timezone.now)),
                ('address', models.TextField(max_length=200)),
                ('image', models.ImageField(upload_to='')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='masters.city')),
                ('hostgame', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='games.hostgame')),
                ('profile_a', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profile_a', to='users.profile')),
                ('profile_b', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profile_b', to='users.profile')),
                ('team_a', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_a', to='users.team')),
                ('team_b', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_b', to='users.team')),
                ('winner_Team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.team')),
                ('winner_player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.teammember')),
            ],
        ),
    ]
